# 默认使用开发配置
spring:
  profiles:
    active: dev
    
#配置mybatis参数
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  
--- 
  
#开发配置
spring:
  profiles: dev

  datasource: 
    url: jdbc:mysql://47.98.125.109:3306/YUIN
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootroot